version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml --web.external-url="http://192.168.48.129:9090/" --web.enable-lifecycle  #填外部访问地址
    volumes:
      - ./prometheus/etc:/etc/prometheus:ro
      - ./prometheus/data:/prometheus/data
    networks:
      - prome-net
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    networks:
     - prome-net
    volumes:
      - "./alert/etc:/etc/alertmanager:ro"
      - "./alert/data:/alertmanager"
  grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        networks:
         - prome-net
        ports:
            - "3000:3000"
  webhook-dingtalk:
    image: timonwong/prometheus-webhook-dingtalk:latest
    container_name: webhook-dingtalk
    volumes:
      - ./dingtalk/dingtalk.yml:/dingtalk/dingtalk.yml
      - ./dingtalk/templates:/templates
    restart: always
    command: --config.file=/dingtalk/dingtalk.yml --web.enable-ui
    ports:
      - 8060:8060
    networks:
      - prome-net

networks:
  prome-net:
    ipam:
      driver: default
      config:
        - subnet: "10.121.79.0/24"